### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by netrusov** [netrusov/grape-cache#1]
- [x] customizable cache backend
- [ ] tests
- [x] maybe allow set different TTL for backend and client cache
- [ ] maybe add expiration by events from `ActiveSupport::Notifications`
